### ISSUE TITLE
Idempotency Issue with Exadata Infrastructure

### ISSUE THREAD

**Issue by terrymandin** [oci-landing-zones/terraform-oci-multicloud-azure#33]
I created an Exadata Infrastructure using the AzAPI Infra call.  When I re-ran my Terraform I got an "Exadata Infrastructure name cannot be reused within the same resource group. Please use a different name" error message.  

To test, follow these steps:

1. Clone https://github.com/sihbher/avm-res-oracledatabase-cloudexadatainfrastructure/tree/main/
2. Run Terraform apply on this [example](https://github.com/sihbher/avm-res-oracledatabase-cloudexadatainfrastructure/tree/main/examples/default)
3. Re-run Terraform apply on the example

Error message
```
Plan: 0 to add, 4 to change, 0 to destroy.
azurerm_resource_group.this: Modifying... [id=/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x]
azurerm_resource_group.this: Modifications complete after 1s [id=/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x]
module.avm_odaa_infra.azapi_resource.odaa_infra: Modifying... [id=/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x/providers/Oracle.Database/cloudExadataInfrastructures/odaa-infra-ig01j]
module.odaa_vnet.azapi_resource.vnet: Modifying... [id=/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x/providers/Microsoft.Network/virtualNetworks/vnet-odaa]module.odaa_vnet.azapi_resource.vnet: Modifications complete after 4s [id=/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x/providers/Microsoft.Network/virtualNetworks/vnet-odaa]
╷
│ Error: Failed to create/update resource
│
│   with module.avm_odaa_infra.azapi_resource.odaa_infra,
│   on ..\..\..\avm-res-oracle-database-cloudexadatainfrastructure-fork\main.tf line 2, in resource "azapi_resource" "odaa_infra":
│    2: resource "azapi_resource" "odaa_infra" {
│
│ creating/updating Resource: (ResourceId
│ "/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x/providers/Oracle.Database/cloudExadataInfrastructures/odaa-infra-ig01j"
│ / Api Version "2023-09-01"): PUT
│ https://management.azure.com/subscriptions/ef2c2154-2d60-433c-a2d8-b947e184c3a7/resourceGroups/rg-bg1x/providers/Oracle.Database/cloudExadataInfrastructures/odaa-infra-ig01j
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: 400
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "400",
│     "message": "Exadata Infrastructure name cannot be reused within the same resource group. Please use a different name"
│   }
│ }
│ --------------------------------------------------------------------------------
│
```

**Comment by chanstev** [comment]
@terrymandin We are not able to reproduce the issue on our end. would you pls share your environment configuration? We can take a look into that. 
![image](https://github.com/user-attachments/assets/96e5cc4b-7eb3-4519-afb4-4fa6ffc42a90)

**Comment by terrymandin** [comment]
@chanstev , thanks for looking into this.  We will re-test on our side.

**Comment by terrymandin** [comment]
@chanstev, we have confirmed that this is still an issue:

![image](https://github.com/user-attachments/assets/6f8757ed-7eb5-4c54-9062-b17946536064)

**Comment by chanstev** [comment]
@terrymandin As discussed, this is related to 2 behaviours as described below, and we will log 2 separate issues for a clearer description of the issue and be followed up accordingly. 
- Update property of Exadata Infra via Azure side is not supported at the moment, neither via Azure Portal or Terraform AzAPI. However, it can be done via interfaces on OCI side. We will follow up as a feature request.
![image](https://github.com/user-attachments/assets/1a4ec429-50e4-4178-96b9-b15e267061b1)
- Due to the above nature, the related metadata (e.g. Azure tagging) has to be updated via azapi_update_resource instead of azapi_resource call. You can find the sample of azapi_update_resource [here](https://github.com/Azure/terraform-provider-azapi/issues/404). We will log a separate issue for supporting Azure tagging to follow up.
