### ISSUE TITLE
VMCluster hostname changes after deploy

### ISSUE THREAD

**Issue by sihbher** [oci-landing-zones/terraform-oci-multicloud-azure#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
After deploy VMCluster (Oracle.Database/cloudVmClusters@2023-09-01), hostname value changes (platform adds an extra token at the end) and this causes that in the next apply operation, Terraform identifies that hostname has changed. Idempotency is not meet

#### First apply (terraform apply)

<img width="779" alt="image" src="https://github.com/user-attachments/assets/62f38485-3b74-4ff2-822c-0dc801ab706e">

#### Before second apply (terraform plan)
<img width="1706" alt="image" src="https://github.com/user-attachments/assets/29555ad3-c42d-468e-9a5f-9167ff699358">

#### Expected behavior
**hostame** property should have the value assigned by te configuration

**Comment by chanstev** [comment]
This hostname field is equivalent to the host name prefix field in the Azure Portal as 
![Screenshot 2024-11-01 at 21 06 00](https://github.com/user-attachments/assets/e4da9e22-682c-4d74-9899-ad57d1e2ec49)
Given that the resource name and displayname has to be identical, we are merging these variables in the template.
